<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="AdminPage.aspx.cs" Inherits="WorldOfNews.Admin.AdminPage" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">

    <h1>Administration</h1>
    <hr />
    <p></p>
    
    <asp:GridView ID="UserManipulationGridView" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AllowPaging="True" AllowSorting="True" DataKeyNames="Id" DataSourceID="SqlDataSource1">
        <Columns>
            <asp:BoundField DataField="Id" HeaderText="Id" ReadOnly="True" SortExpression="Id" />
            <asp:BoundField DataField="UserName" HeaderText="UserName" SortExpression="UserName" />
            <asp:BoundField DataField="Email" HeaderText="Email" SortExpression="Email" />
            <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />
        </Columns>
    </asp:GridView>

     <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:DefaultConnection %>" 
        SelectCommand="SELECT AspNetUsers.Id, AspNetUsers.UserName, AspNetUsers.Email, AspNetRoles.Name FROM AspNetUsers JOIN AspNetUserRoles ON AspNetUsers.Id = AspNetUserRoles.UserId JOIN AspNetRoles ON AspNetUserRoles.RoleId = AspNetRoles.Id"
        DeleteCommand="DELETE FROM [AspNetUsers] WHERE [Id] = @Id"
        UpdateCommand="UPDATE [AspNetUsers] SET [UserName] = @UserName, [Email] = @Email WHERE [Id] = @Id;
                       UPDATE [AspNetRoles] SET [Name] = @Name WHERE [Id] = (SELECT AspNetUserRoles.RoleId from AspNetUsers JOIN AspNetUserRoles ON AspNetUsers.Id = AspNetUserRoles.UserId WHERE AspNetUsers.Id = @Id)">
     </asp:SqlDataSource>

</asp:Content>
