<%@ Page Title="Proposed Articles" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="ProposedArticles.aspx.cs" Inherits="WorldOfNews.Editor.ProposedArticles" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <h1>Proposed Articles</h1>
    <hr />
    <p></p>
    
    <asp:Label ID="LabelAddStatus" Text="" runat="server"></asp:Label>

    <asp:DetailsView CssClass="table table-hover" ID="ProposedArticlesDetails" runat="server" OnItemCommand="DetailsView1_RowCommand" OnRowCommand="DetailsView1_RowCommand" AllowPaging="true" AutoGenerateInsertButton="true" AutoGenerateEditButton="true" AutoGenerateDeleteButton="true" AutoGenerateRows="False" DataKeyNames="ArticleID" DataSourceID="SqlDataSource1" EnableViewState="false">
        <PagerSettings Mode="Numeric" Position="Bottom" />
        <pagerstyle backcolor="LightBlue" height="30px" verticalalign="Bottom" horizontalalign="Center"/>
        <Fields>
            <asp:BoundField DataField="ArticleID" HeaderText="ArticleID" InsertVisible="false" ReadOnly="True" SortExpression="ArticleID" />
            <asp:BoundField DataField="ArticleName" HeaderText="ArticleName" SortExpression="ArticleName" />
            <asp:BoundField DataField="Description" HeaderText="Description" SortExpression="Description" />
            <asp:ImageField HeaderText="Image" ControlStyle-Width="30%" ControlStyle-Height="30%" DataImageUrlField="ImagePath" DataImageUrlFormatString="~/Images/{0}"> </asp:ImageField>
            <asp:BoundField DataField="ImagePath" HeaderText="ImagePath" SortExpression="ImagePath" />
            <asp:BoundField DataField="CategoryID" HeaderText="CategoryID" SortExpression="CategoryID" />
            <asp:ButtonField HeaderText="Save Article" CommandName="AddToArticles" Text="Save"/>
        </Fields>
     </asp:DetailsView>

     <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:DefaultConnection %>" 
        SelectCommand="SELECT ArticleID, ArticleName, Description, ImagePath, CategoryID FROM ProposedArticles"
        DeleteCommand="DELETE FROM [ProposedArticles] WHERE [ArticleID] = @ArticleID"
        UpdateCommand="UPDATE [ProposedArticles] SET [ArticleName] = @ArticleName, [Description] = @Description, [ImagePath] = @ImagePath, [CategoryID] = @CategoryID WHERE [ArticleID] = @ArticleID"
        InsertCommand="SET IDENTITY_INSERT Articles ON; INSERT INTO [Articles] (ArticleID, ArticleName, Description, ImagePath, CategoryID) VALUES ( ((SELECT MAX(ArticleID) FROM Articles) + 1), @ArticleName, @Description, @ImagePath, @CategoryID); SET IDENTITY_INSERT Articles OFF">
         
        <DeleteParameters>
            <asp:Parameter Name="ArticleID" Type="Int32" />
        </DeleteParameters>
        <UpdateParameters>
            <asp:Parameter Name="ArticleName" Type="String" />
            <asp:Parameter Name="Description" Type="String" />
            <asp:Parameter Name="ImagePath" Type="String" />
            <asp:Parameter Name="CategoryID" Type="Int32" />
        </UpdateParameters>
        <InsertParameters>
            <asp:Parameter Name="ArticleID" Type="Int32" />
            <asp:Parameter Name="ArticleName" Type="String" />
            <asp:Parameter Name="Description" Type="String" />
            <asp:Parameter Name="ImagePath" Type="String" />
            <asp:Parameter Name="CategoryID" Type="Int32" />
        </InsertParameters>
     </asp:SqlDataSource>
</asp:Content>
